from .models import ReceiptData
from .serializers import ReceiptDataSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .utils import calculate_points


# Takes in a JSON receipt (see example in the example directory) and returns a JSON object with an ID generated by your code.
# The ID returned is the ID that should be passed into /receipts/{id}/points to get the number of points the receipt was awarded.
@api_view(['POST'])
def CreateReceipt(request):
    serializer = ReceiptDataSerializer(data= request.data)
    if serializer.is_valid():
        serializer.save(points=calculate_points(request.data))
        return Response({"id": serializer.data['id'] }, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# A simple Getter endpoint that looks up the receipt by the ID and returns an object specifying the points awarded.
@api_view(['GET'])
def RetrieveReceipt(request, pk):
    try:
        receipt = ReceiptData.objects.get(id = pk)
    except ReceiptData.DoesNotExist:
        return Response(status=status.HTTP_400_BAD_REQUEST)
    serializer = ReceiptDataSerializer(receipt)
    return Response({ "points": serializer.data['points'] })
    